name: Deploy Pull Requests for Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
          include-prerelease: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./CyberForceWeb.Web/package-lock.json

      - name: Restore and Install npm Packages
        run: |
          cd ./CyberForceWeb.Web
          npm ci
          npm run build
          
      - name: Build and Restore with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        if: github.event_name != 'pull_request'
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/CyberForceWeb

      - name: Upload artifact for deployment job
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/CyberForceWeb
  
  deploy-for-testing:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Pull Request'
      url: ${{ steps.deploy-to-testing-webapp.outputs.webapp-url }}

    steps:
      - name: Clean up old docs
        run:  
          Get-Process | foreach{$processVar = $_;$_.Modules | foreach{if($_.FileName -eq ((get-location).path + "\CyberForceWeb.Web.dll")){taskkill /F /PID $processVar.id}}}
        
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Run new version
        run:  
          dotnet CyberForceWeb.Web.dll
