name: Test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    environment:
      name: 'Pull Request'
      url: ${{ steps.deploy-to-testing-webapp.outputs.webapp-url }}

    steps:
      - name: Clean up old docs
        run:  
          Get-Process | foreach{$processVar = $_;$_.Modules | foreach{if($_.FileName -eq ((get-location).path + "\CyberForceWeb.Web.dll")){taskkill /F /PID $processVar.id}}}

      - name: Run new version
        run:  
          RUNNER_TRACKING_ID="" && (start powershell {dotnet CyberForceWeb.Web.dll})
